###############################################
########## Physical robot parameters ##########
###############################################

robot:
  name: "yumi_single_arm"
  ip_robot: "192.168.131.200"
  robot_port_rws: 443
  # ip_robot: "192.168.56.101" # for virtual robot (robotstudio)
  # robot_port_rws: 80 # for virtual robot (robotstudio)
  name_robot: "ROB_1"
  task_robot: "T_ROB1"
  pos_corr_gain: 1
  max_speed_deviation: 300
  robot_port_egm: 6511
  root_name: "base"
  tip_name: "L6"

###############################################
#### Settings for ros_control control loop ####
###############################################

robot_hw_control_loop:
  loop_hz: 100
  cycle_time_error_threshold: 0.004

###############################################
# Settings for ros_control hardware interface #
###############################################

robot_hardware_interface:
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7

###############################################
############# Loading controllers  ############
###############################################

joint_state_controller:
  type:         joint_state_controller/JointStateController
  publish_rate: 100

###############################################
######### Joint Trajectory Controller  ########
###############################################
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
robot_controller:
  type: position_controllers/JointTrajectoryController
  # These joints can likely just be copied from the hardware_interface list above
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
  constraints:
    goal_time: 5.0
    #stopped_position_tolerance: 0.4 # Defaults to 0.01
    joint_1:
      trajectory: 0.2
      goal:       0.01
    joint_2:
      trajectory: 0.2
      goal:       0.01
    joint_3:
      trajectory: 0.2
      goal:       0.01
    joint_4:
      trajectory: 0.2
      goal:       0.01
    joint_5:
      trajectory: 0.2
      goal:       0.01
    joint_6:
      trajectory: 0.2
      goal:       0.01
    joint_7:
      trajectory: 0.2
      goal:       0.01
   # gains:
   #     joint1: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}
   #     joint2: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}
   #     joint3: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}
   #     joint4: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}
   #     joint5: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}
   #     joint6: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}
   #     joint7: {p: 2.0,  i: 0.0, d: 0.01, i_clamp: 1}

  state_publish_rate:  100     # Defaults to 50
  #action_monitor_rate: 20     # Defaults to 20
  #hold_trajectory_duration: 0 # Defaults to 0.5